### PR TITLE
Handle composer versions without composer/semver enabled

### LINKED ISSUE #8: Semver not found on global install
```bash
oskar.stark:~$ composer global require sllh/composer-versions-check
Changed current directory to /Users/oskar.stark/.composer
Using version ^1.0 for sllh/composer-versions-check
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sllh/composer-versions-check (v1.0.0)
    Downloading: 100%

Writing lock file
Generating autoload files
PHP Fatal error:  Class 'Composer\Semver\Constraint\Constraint' not found in /Users/oskar.stark/.composer/vendor/sllh/composer-versions-check/src/VersionsCheck.php on line 34
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/composer:0
PHP   2. require() /usr/local/bin/composer:25
PHP   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
PHP   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   8. Composer\Command\GlobalCommand->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   9. Composer\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Command/GlobalCommand.php:80
PHP  10. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
PHP  11. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP  12. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
PHP  13. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP  14. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP  15. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP  16. Composer\Installer->run() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:158
PHP  17. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///usr/local/bin/composer/src/Composer/Installer.php:344
PHP  18. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:92
PHP  19. call_user_func:{phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:152}() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:152
PHP  20. SLLH\ComposerVersionsCheck\VersionsCheckPlugin->postUpdate() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:152
PHP  21. SLLH\ComposerVersionsCheck\VersionsCheckPlugin->checkVersions() /Users/oskar.stark/.composer/vendor/sllh/composer-versions-check/src/VersionsCheckPlugin.php:61
PHP  22. SLLH\ComposerVersionsCheck\VersionsCheck->checkPackages() /Users/oskar.stark/.composer/vendor/sllh/composer-versions-check/src/VersionsCheckPlugin.php:75

Fatal error: Class 'Composer\Semver\Constraint\Constraint' not found in /Users/oskar.stark/.composer/vendor/sllh/composer-versions-check/src/VersionsCheck.php on line 34

Call Stack:
    0.0034     233328   1. {main}() /usr/local/bin/composer:0
    0.0115     419560   2. require('phar:///usr/local/bin/composer/bin/composer') /usr/local/bin/composer:25
    0.0374    3618992   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43
    0.0392    3965096   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
    0.0398    4097976   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0405    4208296   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
    0.0405    4208736   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0410    4209064   8. Composer\Command\GlobalCommand->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0470    4434080   9. Composer\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Command/GlobalCommand.php:80
    0.0470    4434080  10. Symfony\Component\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
    0.0472    4434224  11. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0482    4436720  12. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
    0.0483    4436720  13. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0483    4437120  14. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0486    4442752  15. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    5.1672   52838928  16. Composer\Installer->run() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:158
   10.3788  117029112  17. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///usr/local/bin/composer/src/Composer/Installer.php:344
   10.3788  117029552  18. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:92
   10.3794  117030608  19. call_user_func:{phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:152}() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:152
   10.3794  117030736  20. SLLH\ComposerVersionsCheck\VersionsCheckPlugin->postUpdate() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:152
   10.3794  117030888  21. SLLH\ComposerVersionsCheck\VersionsCheckPlugin->checkVersions() /Users/oskar.stark/.composer/vendor/sllh/composer-versions-check/src/VersionsCheckPlugin.php:61
   10.3794  117031064  22. SLLH\ComposerVersionsCheck\VersionsCheck->checkPackages() /Users/oskar.stark/.composer/vendor/sllh/composer-versions-check/src/VersionsCheckPlugin.php:75

oskar.stark:~$
```

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #8.

On some composer versions, semver package is not available.

In this case, use the old comparator and version constraint.

I added a special case on Travis for this: https://travis-ci.org/Soullivaneuh/composer-versions-check/jobs/83852780

Thanks @OskarStark for issue reporting. :+1:

### CODE REVIEW

**Comment by OskarStark** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
New patch version incoming.

File: src/VersionsCheck.php [hunk 1]
```diff
@@ -65,6 +79,29 @@ public function getOutput()
...
+     * This method is public only for PHP 5.3 BC and SHOULD NOT be used.
+     * Deprecate it and remove it on next major when PHP 5.3 support will be droped.
+     *
+     * @param string $version1
+     * @param string $operator
+     * @param string $version2
+     *
+     * @return bool
+     */
+    public function versionCompare($version1, $operator, $version2)
```
Comment (OskarStark) [inline src/VersionsCheck.php]: what about making this method private to keep it in the lib scope?

File: src/VersionsCheck.php [hunk 2]
```diff
@@ -65,6 +79,29 @@ public function getOutput()
         return implode("\n", $output)."\n";
```
Comment (OskarStark) [inline src/VersionsCheck.php]: PHP_EOL?

Comment (Soullivaneuh) [inline src/VersionsCheck.php]: Already done in #11.

File: src/VersionsCheck.php (hunk 1 above)
Comment (Soullivaneuh) [inline src/VersionsCheck.php]: I have to make it public to be BC with the ugly PHP 5.3. See method comment. :-)

**Comment by Soullivaneuh** [comment]
Tagged: https://github.com/Soullivaneuh/composer-versions-check/releases/tag/v1.0.1
